// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUNeB31o4euPsMv_Tu-iwHo-RRKh0hwrY',
    appId: '1:850726374177:web:f51d7edc7428494113cc60',
    messagingSenderId: '850726374177',
    projectId: 'reddit-b2512',
    authDomain: 'reddit-b2512.firebaseapp.com',
    storageBucket: 'reddit-b2512.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5R-LR5-7PD9eq2J3z4xuhx8kMs7aQWZU',
    appId: '1:850726374177:android:727f827bf47fb4c613cc60',
    messagingSenderId: '850726374177',
    projectId: 'reddit-b2512',
    storageBucket: 'reddit-b2512.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2d2Dc-QGFb5d95i-SYxP2zFl7i0ZRTRY',
    appId: '1:850726374177:ios:7b0626de6c258c7a13cc60',
    messagingSenderId: '850726374177',
    projectId: 'reddit-b2512',
    storageBucket: 'reddit-b2512.appspot.com',
    iosBundleId: 'com.bitwisedhruv.reddit',
  );
}
